version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g --silent react-scripts
      - npm install -g --silent serverless
  build:
    commands:
      - npm run build
